name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.0.8
      env:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN }}
          REMOTE_HOST: '39.105.220.73'
          REMOTE_USER: 'root'
          SOURCE: 'dist/'
          TARGET: '/var/www/html/bookshop/'
          ARGS: '-avzr --delete'
